language: node_js
node_js: node
addons:
  jwt:
    secure: H9giPDSLgZsSJbhP/upd7lKEduB+0pdL3H1+EoLKASZVCXQG3Qn1Urxwes1iv+tjKOoXeKumlxXfj7QoIEjtSdlrA98KkLHU0AhH1kj2ARwLsMzkQY4UaAsVkmfTVGKW5YcZMeM0y89hxXxtnLGPMKMn+u6NRtlALli2xdBed1lQkZ6qRXY2SF6Qjc5vSfmjBmd+PkpK3P1OXiO2l5juqF9B2CjZuyC1UlEVVo7U4CiENEhXuQdu396jfvZou4QIjr7GhBTxHw2z151Y5Fj3asrPmLYFjs14JZa6i19PfgVE43FEU/GYdACPDxJDpupE80Vfb/COARyKjsrynNzJv2Z1E0iK2kZmex6m2kR+IZQlifKIFpf7nWkiPoJVV/GrH/MW5bsMG+PilS1QhYPFg6BAQwb3P3dURrNcPslD6yYH3f3A1xWuj1U5o8f7Q4HHs6ofMtOc27p7f2kVr2D+T+y5gTGJNBCuTZu56MsCjDXCyrDRPYxnQpvQILcdZ8haN+DjNu9UYcnmVRIAjiYhQXCAvVGbtM+eHYJz3cCXClN8qNl3RsOwQIJ7FpETsl2aHt9SKJv/17JiZzKgkSaEguSxCEGFqcz/E9f395K4rb8U5objEm80/cKk+WgP0ORVN+fapzvSKJO493ok0mF2cMwcxV9aRpSVahQ09ruRSUw=
script:
- npm run lint
- polymer test --skip-plugin local
env:
  global:
    SAUCE_USERNAME: Desire2Learn
