language: node_js
node_js: stable
addons:
  firefox: latest
  apt:
    packages:
    - oracle-java8-installer
    - oracle-java8-set-default
before_script:
- npm run test:lint:js
- npm run test:lint:wc
script:
- xvfb-run npm run test:unit