language: node_js
node_js: node
script:
- npm run lint
- 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then polymer test --skip-plugin local; fi'
- 'if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then polymer test --skip-plugin sauce; fi'
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  # SAUCE_ACCESS_KEY
  - secure: Akbd3K1zb9UVsXF1rFRwtg4CJW2vEXjKw1adshZ0IqhY4S9os/1B01joEPjeGSCRmmR5w0e3IlLrIKBv8oF12939WpBE/jBu2vW/5aiPSzzOwkSO9USvb4ilfqwGc9v7IR7A3nOICuCdwv7wSiPegpFO3YQy1dtHxpVsFRRTeprNQBKSH2/OHbDzbzz+GZab1iLtmLwvkZREBnUiERUkm1JbwUBPyhILwmHdT49QDth5hODK8GJSLYAl6KhGMPFEOkKe7LuTY83iHBv5R7JxdnHopHumlcw6EcVEziN9AJOKREl7N9yaMuRUlz4IeI1qGFIzqvZsMmPKFgt9nJ4Vcw8z8NXr2PPsCD4vuMoAP7n2phFsWY4Noh0QAlLcq6ZmRbeRFNgqs69mcob1Z21PMLkd8F+s13m0rkp04wARVzmNK4u1Eyi69s7nGYDMvUMLFHjScBkohQCrYkxHdvmowYccC12WCUZUMCp3ryoUzDbJYcskQnYyU+JKpadr2rJlo+VafB+KPAUljyJvofWAWEpAJ6CfYO2S0SWUQhY3v3TfAmvDuAmKDjqXky/UOa/kMK+Udi05qqw93kHR1YCPTyuC1+FeNT19nr6Y2zFBjDqPcFTgMPP/0sO5L99MfZ7o9QUaHfU0uXqaJmFzn5Tj6S6rmzAa7vlPO7g7vBKQmN0=
